version: '3'

services:
  app:
    build: 
      context: .
    ports:
      - 3000:3000
    container_name: 'devlevi-prod'
    restart: always
    stdin_open: true
    tty: true
    networks:
        - projects
networks: 
  projects:
    driver: bridge
