version: '3'

services:
  app:
    build: 
      context: .
      target: deps
    ports:
      - 3000:3000
    container_name: 'devlevi'
    stdin_open: true
    tty: true
    networks:
      - projects
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: npm run dev
networks:
  projects:
    driver: bridge
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
