version: '3'

services:
  app:
    build: 
      context: .
    ports:
      - 3000:3000
    container_name: 'devlevi'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
